### ISSUE TITLE
User : User Fund History should be there in Menu, Under Add Funds

### ISSUE THREAD

**Issue by santhu15j** [santhu15j/web-bow#15]
User : User Fund History should be there in Menu, Under Add Funds

![user funds history](https://user-images.githubusercontent.com/28134305/48414000-6d8ad000-e76f-11e8-8155-85c00d6d561d.png)

With page navigation like Order History, And a Search Option

**Comment by chetan3** [comment]
Api is already there.. 
http://{{domain_add}}/mediaPromotion/user/getWalletHistory
@prasath-k

**Comment by santhu15j** [comment]
@prasath-k   Please Check this, and Finish this ASAP
