### ISSUE TITLE
User: Order Progress Bar Data should be real-time, PENDING, IN PROGRESS, REFUNDED, COMPLETED

### ISSUE THREAD

**Issue by santhu15j** [santhu15j/web-bow#5]
User: Order Progress Bar Data should be real-time, PENDING, IN PROGRESS, REFUNDED, COMPLETED

Currently, the default values are showing

![likesworld](https://user-images.githubusercontent.com/28134305/47135637-b49bb780-d2ce-11e8-9980-ef2157f8939a.png)

This values should show 0 for new account once placing order based on status this numbers should update

**Comment by chetan3** [comment]
Has to be done..

**Comment by chetan3** [comment]
Its done for both Admin and User
Admin -- http://{{domain_add}}/mediaPromotion/admins/getAllOrderStatusBar @jyothishkumarts 
User -- http://{{domain_add}}/mediaPromotion/user/getOrderStatusBar @prasath-k

**Comment by santhu15j** [comment]
@prasath-k   Please chec this API is done, Please update front-end ..
