### ISSUE TITLE
User : After Placing order show a conformation Pop Up

### ISSUE THREAD

**Issue by santhu15j** [santhu15j/web-bow#6]
After Placing order show a conformation Pop Up

With the order details,

![order success](https://user-images.githubusercontent.com/28134305/47153323-e88dd180-d2fc-11e8-9c20-b21f948cc4f0.png)

**Comment by chetan3** [comment]
It should be done from frontend side.

**Comment by chetan3** [comment]
Its already done... Frontend implementation has to be done

**Comment by santhu15j** [comment]
@prasath-k     Please Check this, and Finish this ASAP

ALSO @chetan3  is giving Available User Balance after placing this order so show that also 


![order success](https://user-images.githubusercontent.com/28134305/48837727-1ce92780-edac-11e8-9d72-fcb77fb1f23b.png)

**Comment by ajitkalindri59-stack** [comment]
HBO

**Comment by ajitkalindri59-stack** [comment]
100

**Comment by ajitkalindri59-stack** [comment]
<img width="720" height="1600" alt="Image" src="https://github.com/user-attachments/assets/3b81f2e6-2b06-4eac-a461-70d1ffcb393b" />

**Comment by ajitkalindri59-stack** [comment]
<img width="720" height="1600" alt="Image" src="https://github.com/user-attachments/assets/9aebe563-f36f-45ff-9d87-9b7b464fcad9" />
